# Inserts a blank line between shell prompts
add_newline = false

# allow some commands to startup (especially on first calls)
command_timeout = 1500

# format = """

# ($all)
# $directory$character
# """

# more custom prompt
format = """
($aws\
$azure\
$battery\
$buf\
$bun\
$c
$cmake\
$cmd_duration\
$cobol\
$conda\
$container\
$crystal\
$daml\
$dart\
$deno\
$docker_context\
$dotnet\
$elixir\
$elm\
$env_var\
$erlang\
$gcloud\
$git_branch\
$git_commit\
$git_metrics\
$git_state\
$git_status\
$golang\
$guix_shell\
$haskell\
$haxe\
$helm\
$hg_branch\
$hostname\
$java\
$jobs\
$julia\
$kotlin\
$kubernetes\
$localip\
$lua\
$memory_usage\
$meson\
$nim\
$nix_shell\
$nodejs\
$ocaml\
$opa\
$openstack\
$os\
$package\
$perl\
$php\
$pulumi\
$purescript\
$python\
$raku\
$red\
$rlang\
$ruby\
$rust\
$scala\
$shell\
$shlvl\
$singularity\
$spack\
$status\
$sudo\
$swift\
$terraform\
$username\
$vagrant\
$vcsh\
$vlang\
$zig)
$directory$character
"""

[aws]
symbol = "  "

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"

[cmd_duration]
min_time = 30
show_milliseconds = false
disabled = false
format = "祥$duration($style) "
style = "bold italic #87A752"

[conda]
symbol = " "
# format = "[$symbol$environment](dimmed green) "

[dart]
symbol = " "

[directory]
read_only = " "
truncate_to_repo = true

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[git_branch]
symbol = " "

[golang]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[line_break]
disabled = true

[memory_usage]
symbol = " "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[package]
symbol = " "

[rust]
symbol = " "

[time]
disabled = false
