theme = "fleet_dark"

[editor]
auto-save = false  # saves on unfocus
# rulers = [80, 120]
color-modes = true
bufferline = "multiple"
scroll-lines = 2
mouse = false

[editor.lsp]
display-messages = true

[keys.normal]
H = "goto_line_start"
L = ["goto_line_end", "move_char_right"]
# J = "half_page_down"
# K = "half_page_up"
g = { e = ["goto_last_line", "move_line_down"] }

[keys.insert]
j = { k = "normal_mode" }
C-s = ':w'
