[[language]]
name = "json"
config = { "provideFormatter" = true, "json" = { "keepLines" = { "enable" = true } } }


[[language]]
name = "markdown"
file-types = ["md"]
scope = "source.markdown"
roots = []


[[languge]]
name = "yaml"

[languge.indent-guides]
render = true
character = "╎" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1


[[language]]
name = "html"

[language.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
"'" = "'"
'`' = '`'
'<' = '>'


[[language]]
name = "plaintext"
scope = "source.plaintext"
file-types = ["txt"]
rulers = [80, 120]
roots = []

[[language]]
name = "python"
rulers = [120]

[config.pylsp]
configurationSources = ['flake8']

[config.pylsp.plugins]
flake8.enabled = true
flake8.config = "/Users/hollandgibson/CVS_Documents/actionmapgeneration/application/LogProcessor/.flake8"
pycodestyle.enabled = false
mccabe.enabled = false
pyflakes.enabled = false


[[language]]
name = "rust"
rulers = [120]

[language.config]
checkOnSave = { command = "clippy" }

[language.debugger]
command = "codelldb"
name = "codelldb"
port-arg = "--port {}"
transport = "tcp"

[[language.debugger.templates]]
name = "binary"
request = "launch"
[[language.debugger.templates.completion]]
completion = "filename"
name = "binary"

[language.debugger.templates.args]
program = "{0}"
runInTerminal = true

