# json
[[language]]
name = "json"
# config = { "provideFormatter" = true, "json" = { "keepLines" = { "enable" = true } } }

[language-server.vscode-json-language-server.config]
provideFormatter = true

[language-server.vscode-json-language-server.config.json]
keepLines = {"enable" = true}


# markdown
[[language]]
name = "markdown"
file-types = ["md"]
scope = "source.markdown"
roots = []


# yaml
[[language]]
name = "yaml"

[languge.indent-guides]
render = true
character = "╎" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1


# html
[[language]]
name = "html"

[language.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
"'" = "'"
'`' = '`'
'<' = '>'


# txt
[[language]]
name = "plaintext"
scope = "source.plaintext"
file-types = ["txt"]
rulers = [80, 120]
roots = []


# python
[[language]]
name = "python"
rulers = [120]

[language-server.pylsp.config]
configurationSources = ['flake8']

[language-server.pylsp.config.plugins]
flake8.enabled = true
flake8.config = "/Users/hollandgibson/CVS_Documents/actionmapgeneration/application/LogProcessor/.flake8"
pycodestyle.enabled = false
mccabe.enabled = false
pyflakes.enabled = false


# rust
[[language]]
name = "rust"
rulers = [120]

[language-server.rust-analyzer.config]
checkOnSave = { command = "clippy" }

[language.debugger]
command = "codelldb"
name = "codelldb"
port-arg = "--port {}"
transport = "tcp"

[[language.debugger.templates]]
name = "binary"
request = "launch"
[[language.debugger.templates.completion]]
completion = "filename"
name = "binary"

[language.debugger.templates.args]
program = "{0}"
runInTerminal = true


# XML
[[language]]
# https://github.com/redhat-developer/vscode-xml/tree/main
name = "xml"
auto-format = false
language-server = { command = "lemminx-linux", args = ["--stdio"] }
# language-servers = [ { command = "lemminx-linux", args = ["--stdio"] } ]
